import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './CustomerDashboard.css';
import './AdminDashboard.css';
import './GenerateReport.css'; // Keep regarding specific report widget styles

const GenerateReport = () => {
    const navigate = useNavigate();
    const [selectedReport, setSelectedReport] = useState('sales');
    const [dateRange, setDateRange] = useState({ start: '', end: '' });
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedReports, setGeneratedReports] = useState([
        { id: 1, name: 'Sales_Report_Jan_2026.html', type: 'Sales', date: 'Jan 31, 2026', size: '1.2 MB' },
        { id: 2, name: 'User_Activity_Jan_2026.html', type: 'User Activity', date: 'Jan 31, 2026', size: '2.5 MB' },
        { id: 3, name: 'Inventory_Log.html', type: 'Inventory', date: 'Jan 15, 2026', size: '850 KB' },
    ]);

    const handleLogout = () => {
        navigate('/signin');
    };

    const handlePrintReport = () => {
        setIsGenerating(true);
        setTimeout(() => {
            setIsGenerating(false);
            window.print();
        }, 1500);
    };

    const handleDownloadReport = (report) => {
        // Create a dummy HTML content for the report
        const reportContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${report.name}</title>
                <style>
                    body { font-family: sans-serif; padding: 2rem; color: #1e293b; }
                    h1 { color: #007aff; border-bottom: 2px solid #e2e8f0; padding-bottom: 1rem; }
                    .report-meta { color: #64748b; margin-bottom: 2rem; }
                    .badge { display: inline-block; padding: 0.25rem 0.5rem; background: #f1f5f9; color: #475569; border-radius: 4px; font-weight: bold; font-size: 0.8rem; margin-left: 1rem; }
                    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
                    th, td { border: 1px solid #e2e8f0; padding: 0.75rem; text-align: left; }
                    th { background: #f8fafc; }
                    .footer { margin-top: 3rem; font-size: 0.8rem; color: #94a3b8; text-align: center; }
                </style>
            </head>
            <body>
                <h1>
                    ${report.type} Report 
                    <span class="badge">DRAFT</span>
                </h1>
                <div class="report-meta">
                    <p><strong>Generated Date:</strong> ${report.date}</p>
                    <p><strong>Report ID:</strong> ${report.id}</p>
                </div>
                
                <h2>Summary</h2>
                <p>This is a detailed report for ${report.type}. It contains all relevant data points and analysis for the specified period.</p>
                
                <h3>Service Breakdown</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Service Type</th>
                            <th>Count</th>
                            <th>Revenue</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Wash & Fold</td>
                            <td>120</td>
                            <td>Rs. 45,000</td>
                            <td>Active</td>
                        </tr>
                        <tr>
                            <td>Dry Cleaning</td>
                            <td>45</td>
                            <td>Rs. 32,500</td>
                            <td>Active</td>
                        </tr>
                        <tr>
                            <td>Ironing</td>
                            <td>80</td>
                            <td>Rs. 12,000</td>
                            <td>Active</td>
                        </tr>
                    </tbody>
                </table>

                <div class="footer">
                    Generated by WashTub Laundry System
                </div>
            </body>
            </html>
        `;

        const blob = new Blob([reportContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = report.name; // This will download as .html
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="dashboard">
            {/* Sidebar */}
            <aside className="dashboard-sidebar">
                <div className="sidebar-header">
                    <h2 className="logo">WashTub</h2>
                </div>

                <nav className="sidebar-nav">
                    <Link to="/admin-dashboard" className="nav-item">
                        <span>Overview</span>
                    </Link>
                    <Link to="/user-management" className="nav-item">
                        <span>User Management</span>
                    </Link>
                    <Link to="/service-management" className="nav-item">
                        <span>Service Management</span>
                    </Link>
                    <Link to="/all-orders" className="nav-item">
                        <span>All Orders</span>
                    </Link>
                    <Link to="/payment" className="nav-item">
                        <span>Payment</span>
                    </Link>
                    <a href="#" className="nav-item active">
                        <span>Generate Reports</span>
                    </a>
                    <Link to="/system-settings" className="nav-item">
                        <span>System Settings</span>
                    </Link>
                </nav>

                <button className="logout-btn" onClick={handleLogout}>
                    <span>Logout</span>
                </button>
            </aside>

            {/* Main Content */}
            <main className="dashboard-main">
                <header className="dashboard-header">
                    <div className="header-content">
                        <div className="header-left">
                            <h1>Generate Reports</h1>
                            <p>Create and download detailed system reports</p>
                        </div>
                        <div className="header-right">
                            <button
                                className="btn btn-primary"
                                onClick={() => {
                                    document.getElementById('report-form-section')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                                }}
                                style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.65rem 1.4rem', fontSize: '0.95rem', borderRadius: '10px' }}
                            >
                                <span style={{ fontSize: '1.1rem', lineHeight: 1 }}>+</span> Add New Report
                            </button>
                        </div>
                    </div>
                </header>

                <div className="dashboard-content report-content">
                    {/* Generator Section */}
                    <section id="report-form-section" className="dashboard-form-section">
                        <h2 style={{ fontSize: '1.15rem', fontWeight: 700, color: '#0f172a', margin: '0 0 1.25rem 0' }}>Create New Report</h2>

                        <div className="report-types">
                            <label className={`report-type-card ${selectedReport === 'sales' ? 'selected' : ''}`}>
                                <input type="radio" name="reportType" value="sales" onChange={(e) => setSelectedReport(e.target.value)} checked={selectedReport === 'sales'} />
                                <span className="type-icon">💰</span>
                                <span className="type-label">Sales Report</span>
                                <span className="type-desc">Revenue, transaction history, and financial summaries.</span>
                            </label>

                            <label className={`report-type-card ${selectedReport === 'users' ? 'selected' : ''}`}>
                                <input type="radio" name="reportType" value="users" onChange={(e) => setSelectedReport(e.target.value)} checked={selectedReport === 'users'} />
                                <span className="type-icon">👥</span>
                                <span className="type-label">User Activity</span>
                                <span className="type-desc">New registrations, active users, and customer growth.</span>
                            </label>

                            <label className={`report-type-card ${selectedReport === 'orders' ? 'selected' : ''}`}>
                                <input type="radio" name="reportType" value="orders" onChange={(e) => setSelectedReport(e.target.value)} checked={selectedReport === 'orders'} />
                                <span className="type-icon">📦</span>
                                <span className="type-label">Order Volume</span>
                                <span className="type-desc">Order status breakdown, pickup/delivery stats.</span>
                            </label>

                            <label className={`report-type-card ${selectedReport === 'inventory' ? 'selected' : ''}`}>
                                <input type="radio" name="reportType" value="inventory" onChange={(e) => setSelectedReport(e.target.value)} checked={selectedReport === 'inventory'} />
                                <span className="type-icon">🧼</span>
                                <span className="type-label">Inventory Log</span>
                                <span className="type-desc">Stock levels, usage reports, and supply needs.</span>
                            </label>
                        </div>

                        <div className="date-range-section">
                            <h3>Select Date Range</h3>
                            <div className="date-inputs">
                                <div className="form-group">
                                    <label>Start Date</label>
                                    <input type="date" value={dateRange.start} onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })} />
                                </div>
                                <div className="form-group">
                                    <label>End Date</label>
                                    <input type="date" value={dateRange.end} onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })} />
                                </div>
                            </div>
                        </div>

                        <div className="form-actions">
                            <button className="btn btn-primary btn-large" onClick={handlePrintReport} disabled={isGenerating}>
                                {isGenerating ? (
                                    <>
                                        <span className="spinner"></span> Generating...
                                    </>
                                ) : (
                                    'Print Report'
                                )}
                            </button>
                        </div>
                    </section>

                    {/* Recent Reports */}
                    <section className="dashboard-table-section" style={{ padding: '2rem' }}>
                        <div className="section-header">
                            <h2>Recent Reports</h2>
                            <span className="reports-count">{generatedReports.length} Files</span>
                        </div>

                        <div className="reports-list">
                            {generatedReports.map(report => (
                                <div key={report.id} className="report-item">
                                    <div className="report-icon">
                                        📄
                                    </div>
                                    <div className="report-info">
                                        <h4>{report.name}</h4>
                                        <p>{report.type} • {report.date} • {report.size}</p>
                                    </div>
                                    <div className="report-actions">
                                        <button className="btn-action btn-download" onClick={() => handleDownloadReport(report)}>
                                            Download HTML
                                        </button>
                                        <button className="btn-action btn-view">
                                            Preview
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>
                </div>
            </main>
        </div>
    );
};

export default GenerateReport;
